menu:
  首页: /
  文字: /archives
  作品: /projects
  生活: /life
  关于: /about

# Avatar
avatar: /images/icons/main.jpg

# Social Links
social:
  github: https://github.com/xwqianbei
  email: 2816739071@qq.com

# Content
excerpt_length: 150
