menu:
  Home: /
  Writing: /archives
  Works: /projects
  Life: /life
  About: /about

# Avatar
avatar: /images/icons/main.jpg

# Social Links
social:
  github: https://github.com/xwqianbei
  email: 2816739071@qq.com

# Content
excerpt_length: 150
